### ISSUE TITLE
🛑 Deploying Solution: Unsere Schulkindbetreuung is down

### ISSUE THREAD

**Issue by h2-deploy-20203399221** [H2-invent/status#15]
In [`53b9610`](https://github.com/H2-invent/status/commit/53b961076fd887b12e6407780d84f70a884a81bb
), Unsere Schulkindbetreuung (https://unsere-schulkindbetreuung.de) was **down**:
- HTTP code: 502
- Response time: 821 ms

**Comment by holzi1005** [comment]
We found the issue and deploying a new update to fix the issue
